version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run server and E2E tests locally or against external URL
          command: |
            if [[ -v CYPRESS_baseUrl ]]; then
              echo Testing external url $CYPRESS_baseUrl
              npm run test:e2e:run
            else
              echo Running local server and testing it
              npm run test:e2e:ci
            fi

      - store_artifacts:
          path: ~/repo/cypress/screenshots
      - store_artifacts:
          path: ~/repo/cypress/videos

workflows:
  version: 2
  tests:
    jobs:
      - build